
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';

export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';

export const PRODUCT_LIST_ALL_CATEGORY_SUCCESS = 'PRODUCT_LIST_ALL_CATEGORY_SUCCESS';

export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS ';

export const MENU_LIST_SUCCESS = 'MENU_LIST_SUCCESS ';

export const ABOUT_LIST_SUCCESS = 'ABOUT_LIST_SUCCESS ';

export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const ADD_TO_CART = 'ADD_TO_CART ';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY ';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY ';
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART ';
export const DELETE_ALL_CART = 'DELETE_ALL_CART ';

export const ADD_TO_WISH = 'ADD_TO_WISH ';
export const DELETE_ITEM_WISH = 'DELETE_ITEM_WISH ';

export const CHECKOUT_ITEM = 'CHECKOUT_ITEM';
